<?php

namespace App\Filament\Patient\Resources\AnalyseResource\Pages;

use App\Filament\Client\Resources\AnalyseResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use App\Filament\Patient\Resources\AnalyseResource\Widgets;

class ListAnalyses extends ListRecords
{
    protected static string $resource = AnalyseResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getHeaderWidgets(): array
    {
        return [
            Widgets\BodyTemperature::class,
            Widgets\StepsWalked::class,
            Widgets\WaterChart::class
        ];// TODO: Change the autogenerated stub
    }
}
