<?php

namespace App\Filament\Doctor\Resources\PatientResource\Pages;

use App\Filament\Doctor\Resources\PatientResource;
use Filament\Actions\Action;
use Filament\Forms\Components\Component;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\Page;
use Filament\Resources\Pages\ViewRecord;

class PatientStates extends ViewRecord
{

    protected static string $resource = PatientResource::class;

   protected static string $view = 'filament.doctor.resources.patient-resource.pages.patient-states';

    protected static ?string $title = 'States';

    protected ?string $subheading = 'view different states';
    public function getContentTabLabel(): ?string
    {
        return 'states';// TODO: Change the autogenerated stub
    }

    protected function getViewData(): array
    {
        return [
            'patient' => $this->record,
        ];
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('select day')
                ->form([
                    DateTimePicker::make('starthere')
                        ->label('start from'),

                    DateTimePicker::make('end')
                        ->id('end')
                        ->label('stop date'),
                ])->action(function(Form $form){
                    $data = [];
                    foreach ($form->getComponents() as $component){
                        $data[$component->getStatePath(false)] = $component->getState();
                    }

                    dd(request()->url());
                })
        ];
    }

    protected function getHeaderWidgets(): array
    {
        return [
            PatientResource\Widgets\IOTWidget::make([
                'patient_id' => $this->record->id
            ]),
            PatientResource\Widgets\UserDataWidget::make([
                'patient_id' => $this->record->id
            ]),
        ];
    }

}


